apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: lakehouse/hive-metastore:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 9083

          env:
            - name: SERVICE_NAME
              value: metastore

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"